esta salvando infinitamente e não redireciona, fora que no console deu Console Error
FirebaseError: Failed to get document because the client is offline